Repository tailscale/terraform-provider-tailscale, pull requests merged in 2021-08, with the labels that each got.

#27 docs: added the provider configuration env variables
  docs/index.md
Labels: documentation

#28 Fix incorrect HCL in device subnet routes
  docs/resources/device_subnet_routes.md
Labels: documentation

#30 Remove leading whitespace from path
  internal/tailscale/client.go
Labels: bug

#33 Remove whitespace in device subnet route uri
  internal/tailscale/client.go
Labels: bug

#38 Update ACL examples to use jsonencode
  docs/resources/acl.md
  examples/main.tf
Labels: documentation

#37 Support hujson for ACL files
  go.mod
  go.sum
  internal/tailscale/client.go
  internal/tailscale/client_test.go
  tailscale/provider.go
  tailscale/resource_acl.go
  tailscale/resource_acl_test.go
  vendor/github.com/tailscale/hujson/LICENSE
  vendor/github.com/tailscale/hujson/README.md
  vendor/github.com/tailscale/hujson/decode.go
  vendor/github.com/tailscale/hujson/encode.go
  vendor/github.com/tailscale/hujson/fold.go
  vendor/github.com/tailscale/hujson/fuzz.go
  vendor/github.com/tailscale/hujson/indent.go
  vendor/github.com/tailscale/hujson/pack.go
  vendor/github.com/tailscale/hujson/parse.go
  vendor/github.com/tailscale/hujson/scanner.go
  vendor/github.com/tailscale/hujson/standard.go
  vendor/github.com/tailscale/hujson/stream.go
  vendor/github.com/tailscale/hujson/tables.go
  vendor/github.com/tailscale/hujson/tags.go
  vendor/github.com/tailscale/hujson/types.go
  vendor/modules.txt
Labels: enhancement
